### PR TITLE
Encode the link text to support UTF8 caracter

### PR DESCRIPTION
**Pull request by jonathanlaf**

### CODE REVIEW

**Comment by freelancephp** [comment]
Jonathan, thanks for you contribution. Unfortunately, the method doesn't work combined with the encoding methods.

Gr, Victor

**Comment by jonathanlaf** [comment]
it was working fine here, could you tell me more about the problem ?

**Comment by freelancephp** [comment]
I didn't get correct output. I think it was messed up later on by the Javscript methods.

Now it's solved within those methods by using a encodeURIComponent in PHP and a decodeURIComponent in JavaScript.

**Comment by freelancephp** [comment]
Thanks for your effort. Appreciate it.

**Pull request merged**
